[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"

[profile.default]
src = "contract/src"
out = "contract/out"
libs = ["contracts/lib"]
solc_version = "0.8.24"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
